dist: trusty
language: node_js
node_js:
- '10'
branches:
  only:
  - master
services:
- docker
env:
- NODE_ENV=test
cache:
  directories:
  - node_modules
install:
- npm install
before_script:
- npm run mount
script:
- npm run lint
- npm run test:coverage
after_success:
- echo build succeeded    
deploy:
  - provider: heroku
    app: diegobarreraci
    api_key:
      secure: "Jq6m5VyBeEADvduR3T0zx4BmuV5vE/D5SeBrdLBrhbDM085OncQSg0RPGDgINWPMJ81xON3/UpsytnaPZgQrkdT0vXoWL5yat6wzvkRQXkXEjVssrH1gnCTZHCXy9oq5KOuH5fRsSi4wd+xyJcus4t7H/MqSNi6u4jlCf8llvmI6ZtPHbZza/v/NYy1pMoEM+2LXyfLHhNkFAaJdN9wlC/g+f5c4maFPYTHjaKiENUVRbw8wg7MA13ZfXbHF9o3OjdCQSgP64n6bDhFJjDdOsUmwYH1lTNsH+vynbPskdjKq8djg3P2RCbyNnGMOIaDB8HkOBK3tqkvfFNzo3S6tK2eDSvRGxE0unQR/RhxiRtCWlnPLZaR+4xFVMvo5Qhdst+gf9yei4UB0Fx29AGhXlT9ov6l+yyB/yh0lxEZL7Drh4fH7vPzXAfLqSQOIbYCnu3WRTsjrD/N4i+K7itRSJ8S7486OMDiHKbHX35PlOv26t1e1sbXIxCdQnosKPlAhKiXg9fMwM2kb0KgD1yLljER/L8KYc5BBLgNKVi9ZSaZ1XzCV/kV2n3gXG+HhUpuWod1sZWRDUSGEZTbSHHs2AzDyvhHNDWjh8LJtCDw8Rsq3MGVzP8m7hHXiT/Ij0CDODAMFJtVjUVICWiWabUOtEbmcna1TFSWtjJZczeWVIIc="
    on:
        branch:
          - master
notifications:
  email: false
