dist: trusty
language: node_js
node_js:
  - "10"

branches:
  only:
    - master

services:
  - docker

env:
  - NODE_ENV=test

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - npm run mount

script:
  - npm run lint
  - npm run coverage

after_success:
  - echo Test successful!

notifications:
  email: false