dist: trusty
language: node_js
node_js:
- '10'
branches:
  only:
  - master
services:
- docker
env:
- NODE_ENV=test
cache:
  directories:
  - node_modules
install:
- npm install
before_script:
- npm run mount
script:
- npm run lint
- npm run test:coverage
after_success:
- echo build succeeded    
deploy:
  - provider: heroku
    app: diegobarreraci
    api_key:
      secure: "jd3WHoeIbrF4nWEU68tzyvRzk85yQVOcyR12yHZt/1I649XN5B0zqilw/OmxM6LplT/kwoh+4dbsmFD9AjhELexNKUPrCq6vXH1wSOFr6aHFsSeL1I6EGx9GJGVXQgyFkD/J1ih+CJPcHpt5ss+Prsf62RGM64eeiXmNFFN8WRsr51WcKZBZQXR38xMIojEyDVzyAzQqgs2C+MCDwDghwbiTd4M7X2e8EPVKPJhnE5mfdpfRaWqvJbLKNjd8Ix8PT0Sf/lgBOsFxXfX3IS+BBG9auK3giRgIu8zEy3LhAoLCkBJlu5ds+9MpbNci8Ycs3+7LmOD/PKTeuG6NZEazsgs5o++Y9eNIblZFKFn2us8r8Yvu1O7YNN9ZVebXEHkJvzl/CTuqafoOPuINJDCA3oaMBTWk6Wu9n66uwAz/2yYUfZQC9TuIufHgzsxs7PpvL5XG+PIKjsqWtg3/fRAR4UtiGKa5wE5LOgUFzCDLSvPDRGUTMt2n/SY0Te0eAfHCn+p73reVR4PegJpFujjPvBoPGnIgsOXTPWbaRtCcF5mxYS4xpJdI8sB3OABqpxsk93dN/jyEa3VRoRWW2e7iH2JB5ReBHyqrul1nTnpR6uKofW72UXnwvjZy/AYp229FbXIPsUYrKyb6ILyyFJCBIB2s0vq0HJOg7E1diGIItc4="
    on:
        branch:
          - master
notifications:
  email: false
