version: '3'
services:
  postgres:
    image: sameersbn/postgresql:10
    ports:
    - "5432:5432"
    environment:
     - DB_NAME=test
     - PG_TRUST_LOCALNET=true
  web:
    build: .
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres