version: '3'
services:
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test
  web:
    build: .
    command: npm test
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      NODE_ENV: test
      DATABASE_URL: postgres://postgres@postgres/test